---
# Title: ntfy
#
# Author: Bitfinity / L. Rutten
# Owner: Vissers Energy Group / L. Rutten
#
# File: tasks/02-apache2.yml
#
# Description:
#    ntfy (pronounced notify) is a simple  
#    HTTP-based pub-sub notification service.
#
# Source(s):
#   - https://ntfy.sh/#free-software
#   - https://docs.ntfy.sh/install/
#
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - apache2

- name: "Apache2 load modules"
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
    - rewrite
    - ssl
  notify: restart_apache2

- name: "Transfer templates"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/ntfy.conf.j2', dest: '/etc/apache2/sites-available/ntfy.conf' }

- name: "Disable default configuration files"
  command: "a2dissite {{ item }}"
  with_items:
    - 000-default.conf
    - default-ssl.conf 
    - 000-default-le-ssl.conf
  notify:
    - restart_apache2

- name: "Enable Apache2 configuration ntfy.conf"
  command: a2ensite ntfy.conf
  notify: restart_apache2

- name: "Configure UFW for Apache2 Webserver"
  community.general.ufw:
    rule: allow
    name: Apache Full
